version: '3.8'

services:
  app:
    container_name: sub-domain-router
    image: nginx:latest
    ports:
      - 443:443 # HTTPS
      - 80:80   # HTTP
    volumes:
      - ./Conf/nginx.conf:/etc/nginx/nginx.conf:ro

networks:
  default:
    external:
      name: router-network