version: '3.8'

services:
  app:
    container_name: sub-domain-router
    image: nginx:latest
    ports:
      - 443:443 # HTTPS
      - 80:80   # HTTP
    volumes:
      - ./Conf/nginx.conf:/etc/nginx/nginx.conf:ro

networks:
  router-network: # Custom network to communicate with external services/containers
    external: true
    name: router-network